#!/usr/bin/env python3
"""Run the US state-window analysis (plan parts) and write PDFs + tables.

  python -m scripts.us_analysis.run --config=config/profiles/garg_weat_dlnews_w10.yml \
      --out_dir=/scratch/network/yh6580/gender-occup/results/analysis_w10 --parts=panel,1,2

Parts: panel (canonical datasets), 1 (validation), 2 (maps / heatmap / change),
2b (explaining differences), 2c (text-survey discrepancy), 3 (case selection),
3s (semantic neighbours of selected cases; loads models), bal (national trends on
a balanced panel from 2000-09), figs (combined figures
following the plan's recommended figure structure).
Each part writes <out_dir>/partX_summary.md; figures/tables go to
<out_dir>/main/ and <out_dir>/robustness-*/.
"""

from __future__ import annotations

from pathlib import Path

import fire
import pandas as pd


def main(config: str, out_dir: str, parts: str = "panel,1,2,2b,2c,3,3s,bal,figs") -> None:
    out = Path(out_dir)
    # fire parses "1,2" as a tuple of ints; accept both forms
    items = parts if isinstance(parts, (list, tuple)) else str(parts).split(",")
    todo = [str(p).strip() for p in items if str(p).strip()]
    if not todo:
        raise SystemExit(f"no parts selected from {parts!r}")
    data = out / "data"
    if "panel" in todo or not (data / "state_window_panel.csv").exists():
        from scripts.us_analysis.panel import build_panel
        build_panel(config, out_dir)
    panel = pd.read_csv(data / "state_window_panel.csv")
    cells = pd.read_csv(data / "occupation_cells.csv")
    terms = pd.read_csv(data / "household_terms.csv")

    if "1" in todo:
        from scripts.us_analysis.part1 import run_part1
        print(run_part1(panel, cells, out))
    if "2" in todo:
        from scripts.us_analysis.part2 import run_part2
        print(run_part2(panel, config, out))
    if "2b" in todo:
        from scripts.us_analysis.part2b import run_part2b
        print(run_part2b(panel, config, out))
    if "2c" in todo:
        from scripts.us_analysis.part2c import run_part2c
        print(run_part2c(panel, config, out))
    if "3" in todo:
        from scripts.us_analysis.part3 import run_part3
        print(run_part3(panel, cells, terms, out))

    if "3s" in todo:
        from scripts.us_analysis.semantics import run_semantics
        print(run_semantics(config, out))

    if "bal" in todo:
        from scripts.us_analysis.balanced import run_balanced
        print(run_balanced(panel, cells, terms, out))

    if "figs" in todo:
        from scripts.us_analysis.figures import run_figures
        print(run_figures(panel, out))

    # one combined summary of whatever parts exist
    parts_md = [out / f"part{p}_summary.md" for p in ("1", "2", "2b", "2c", "3", "3s", "_balanced")]
    header = ("# US state-window analysis (3DLNews2) — results\n\n"
              "Generated by `scripts/us_analysis/run.py`; plan: "
              "`docs/us_3dlnews_report/2026-10-05-analysis-plan.md`. Figures (PDF) and tables "
              "(CSV) in `main/`, `validation-*/` (reliability per direct benchmark) and "
              "`robustness-balanced-2000/`; canonical datasets in `data/`. Methods: notes §6.\n"
              "Orientation: state-level scores are higher = less traditional.\n")
    (out / "analysis_summary.md").write_text(
        header + "\n".join(f.read_text() for f in parts_md if f.exists()), encoding="utf-8")


if __name__ == "__main__":
    fire.Fire(main)
